---
- name: find buggy hosts
  hosts: all
  gather_facts: false
  tasks:
  
  
        - command: "df -i"
          async: 2
          poll: 2
          register: df-test
         
        - debug: var=hostvars['target']['def-test']

        - add_host:
            name: "{{ item }}"
            group: available
          when: df-test.finished == 1
          with_items: "{{ groups['all'] }}"
          delegate_to: localhost
          run_once: true
       

- hosts: available
  gather_facts: false
  strategy: free
  tasks:
    #- shell: sleep 1000
    - debug: var=inventory_hostname
    - debug: var=group_names
