---
- name: find buggy hosts
  hosts: all
  gather_facts: false
  tasks:
  
  
        - command: "sleep 10"
          async:   2
          poll:    2
          retries: 1
          ignore_errors: True
          register: df-test
         
        - set_fact:
            df-test: pass          
         
        - debug: var=hostvars['target']
        - debug: var=hostvars['slave']       

        - add_host:
            name: "{{ item }}"
            group: available
          with_items: "{{ groups['all'] }}"
          when: hostvars[item]['df-test'] == 'pass'
          delegate_to: localhost
          run_once: true
       

- hosts: available
  gather_facts: false
  strategy: free
  tasks:
    #- shell: sleep 1000
    - debug: var=inventory_hostname
    - debug: var=group_names
    - debug: var=groups.available
