---
- name:         find buggy hosts
  hosts:        all
  ignore_errors: True
  gather_facts: false
  tasks:
  
        - command:       "sleep 10"
          async:         2
          poll:          2
          retries:       1
          register:      df_test
          
        - debug: var=hostvars['target']
                   
          
        - name: run on tower node
          block:
          - add_host:
              name:      "{{ item }}"
              group:     buggy
            with_items:  "{{ groups['all'] }}"
            #when:        (hostvars[item]['df_test']['rc'] is defined and hostvars[item]['df_test']['rc'] != 0) or (hostvars[item]['df_test']['changed'] == false)
            when: hostvars[item]['df_test']['changed'] == false
            
          - add_host:
              name:      "{{ item }}"
              group:     available
            with_items:  "{{ groups['all'] }}"
            when:        hostvars[item]['df_test']      
          - template:
              src:       email.j2
              dest:      /tmp/buggy_hosts.txt
            when:        groups.buggy is defined
          
          - mail:          
              from:        "{{ email_username }}"
              to:          "{{ email_to }}"
              cc:          "{{ email_cc }}"
              subject:     "{{ email_subject }}"
              attach:      /tmp/buggy_hosts.txt
              body: |
                This email was generated by Ansible.
                The attached list will display the buggy hosts.
                If a host cannot ccomplet this command in 4 seconds, df -i, then it is considered buggy.
                An Ansible admin will be able to use this list of hosts as an inventory source.
            when: groups.buggy is defined
          delegate_to: localhost
          run_once:    true
           
