---
- name: find buggy hosts
  hosts: all
  gather_facts: false
  tasks:
  
  
        - command: "sleep 4"
          async:   2
          poll:    2
          retries: 1
          ignore_errors: True
          register: df_test
         
        - set_fact:
            df_test: pass
          when: df_test.msg is not defined
          
        - set_fact:
            df_test: fail
          when: df_test.msg is defined
         
        - debug: var=hostvars['target']['df_test']
        - debug: var=hostvars['slave']       

        - add_host:
            name: "{{ item }}"
            group: available
          with_items: "{{ groups['all'] }}"
          when: hostvars[item]['df_test'] == 'fail'
          delegate_to: localhost
          run_once: true
       

- hosts: available
  gather_facts: false
  strategy: free
  tasks:
    #- shell: sleep 1000
    - debug: var=inventory_hostname
    - debug: var=group_names
    - debug: var=groups.available
